In [1]:
## import convention 
# numpy -> np
# pandas -> pd
# matplotlib.pyplot -> plt

In [8]:
import numpy as np

In [10]:
data = np.random.randn(2, 3)

In [11]:
data

array([[-0.26050563, -0.92113477,  0.72422698],
       [ 0.33624661,  1.91048222, -0.63592224]])

In [12]:
data * 10

array([[-2.60505634, -9.21134775,  7.24226981],
       [ 3.36246606, 19.10482221, -6.35922244]])

In [13]:
data + data

array([[-0.52101127, -1.84226955,  1.44845396],
       [ 0.67249321,  3.82096444, -1.27184449]])

In [14]:
data.shape

(2, 3)

In [15]:
data.dtype

dtype('float64')

In [16]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)

In [17]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [18]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)

In [19]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [20]:
arr2.ndim

2

In [21]:
arr2.shape

(2, 4)