In [4]:
## import convention 
# numpy -> np
# pandas -> pd
# matplotlib.pyplot -> plt

In [3]:
import numpy as np

In [4]:
data = np.random.randn(2, 3)

In [5]:
data

array([[-0.06127224,  0.74906655,  0.5063797 ],
       [ 2.05299279,  0.66468439,  0.32121717]])

In [6]:
data * 10

array([[-0.61272241,  7.49066553,  5.06379705],
       [20.52992788,  6.64684393,  3.21217174]])

In [7]:
data + data

array([[-0.12254448,  1.49813311,  1.01275941],
       [ 4.10598558,  1.32936879,  0.64243435]])

In [8]:
data.shape

(2, 3)

In [9]:
data.dtype

dtype('float64')

In [10]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)

In [11]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [12]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)

In [13]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [14]:
arr2.ndim

2

In [15]:
arr2.shape

(2, 4)

In [56]:
np.random.rand(2, 3, 2)

array([[[0.17238193, 0.72100541],
        [0.09475076, 0.73588011],
        [0.8964962 , 0.4275943 ]],

       [[0.69822524, 0.43340649],
        [0.64039901, 0.64331145],
        [0.76073884, 0.81108974]]])

In [65]:
np.random.randn(3, 3)

array([[ 0.46657498, -0.36936897,  0.96645192],
       [-0.07083221,  0.59931745,  0.17744024],
       [ 1.47445733,  0.83712909, -1.21755012]])

In [70]:
np.random.randint(1, 100, size=(2, 50))

array([[69, 49, 76, 62, 13, 86, 49, 41, 45,  1, 70,  1, 36, 85, 60, 19,
        41,  2, 58, 51, 24, 68, 41, 80, 43, 81, 57,  9, 70, 87, 18, 59,
        65, 55, 84, 18, 92, 91, 19, 50, 64, 30, 92, 16, 83, 59, 22, 93,
         9, 17],
       [10, 94,  7, 56, 47, 31, 43, 41, 18, 43, 12, 73,  8, 79, 16, 58,
        60, 18, 22, 71, 53, 44, 19, 30,  9, 48, 93, 79, 50, 79, 27, 29,
        90, 82, 75, 33, 89, 88, 67, 91, 70, 19, 30, 19, 81, 18, 41, 35,
        62, 47]])

In [106]:
np.random.seed(1)
np.random.randn(3, 4, 2)

array([[[ 1.62434536, -0.61175641],
        [-0.52817175, -1.07296862],
        [ 0.86540763, -2.3015387 ],
        [ 1.74481176, -0.7612069 ]],

       [[ 0.3190391 , -0.24937038],
        [ 1.46210794, -2.06014071],
        [-0.3224172 , -0.38405435],
        [ 1.13376944, -1.09989127]],

       [[-0.17242821, -0.87785842],
        [ 0.04221375,  0.58281521],
        [-1.10061918,  1.14472371],
        [ 0.90159072,  0.50249434]]])

In [108]:
np.random.choice(100, size=(3, 4))

array([[ 9, 67, 23, 27],
       [37, 57, 83, 38],
       [ 8, 32, 34, 10]])